=== Описание страниц
При работе с `Web plugin` нужно придерживаться паттерна `PageObject`, описывая страницы приложения классами.

*__Страница__* - это класс, внутри которого хранится описание элементов пользовательского UI, а так же действия(actions), которые можно выполнить на этой странице.

Чтобы пользоваться всеми преимуществами плагина, необходимо унаследовать каждую страницу вашего проекта от `WebPage` и именовать страницу при помощи аннотации `@PageEntry`

Пример::
[source,]
----
package ru.sbt.qa.your.project.pages;

import ru.sbtqa.tag.pagefactory.annotations.PageEntry;
import ru.sbtqa.tag.pagefactory.WebPage;

@PageEntry(title = "Ваша страница")
public abstract class YourPage extends WebPage {}
----

По имени, заданному аннотацией `@PageEntry`, можно будет обратиться к странице из тестового сценария.

Путь до корневого каталога с классами страниц должен быть прописан в файле конфигурации (application.properties) в параметре `page.package`.

Пример::
[source,]
----
page.package = ru.sbt.qa.your.project.pages
----

NOTE: [aqua]#Рекомендуется заводить в проекте базовую страницу, унаследованную от `WebPage`, и уже от нее наследовать все остальные. Это позволит в случае необходимости описать ряд действий на базовой странице проекта.#