==== Глагольные выражения
`Web plugin` позволяет описывать шаги, свойственные отдельной странице, непосредственно на ней. Такие шаги называются глагольными выражениями. Они имеют базу в фреймворке и за счет этого их описание сводится к простому именованию методов через специальную аннотацию - `@ActionTitle`. 

Пример::
[source,]
----
@PageEntry(title = "Ваша страница")
public abstract class YourPage extends WebPage {

    @ActionTitle(value = "тестирует")
    public void check() {
        ....
    }
}
----

Чтобы использовать глагольное выражение в тестовом сценарии, достаточно указать его имя в круглых скобках в контексте страницы. Например:

[source,]
----
* открывается страница "Ваша страница"
* (тестирует)
----

Одно глагольное выражение может иметь несколько именований. В этом может быть необходимость, когда есть желание внести конкретику в тестовом сценарии. Сделать это можно при помощи аннотации `@ActionTitles` Например:

[source,]
----
@PageEntry(title = "Ваша страница")
public abstract class YourPage extends WebPage {
    
    @ActionTitles({
        @ActionTitle(value = "тестирует"),
        @ActionTitle(value = "тестирует вашу страницу")
    })
    public void check() {
        ....
    }
}
----

Глагольные выражения могут иметь какие угодно параметры для этого достаточно добавить параметр в сигнатуре метода. Например:

[source,]
----
@PageEntry(title = "Ваша страница")
public abstract class YourPage extends WebPage {

    @ActionTitle(value = "тестирует с параметром")
    public void check(String param) {
        ....
    }
}
----

====
При написании глагольных выражений важно помнить::
* Значение, возвращаемое методом, никуда не сохраняется, поэтому в качестве типа возвращаемого значения стоит всегда указывать void
* В качестве параметров метода можно использовать следующие типы: String, List<String>, DataTable
* Если шага с нужным набором параметров для вашего экшена нет, вы можете написать его сами
====

===== База для глагольных выражений
Как уже говорилось выше, глагольные выражения базируются на уже описанных в `Web plugin`шагах особой структуры. Они приведены ниже

NOTE: Перед шагом можно прописать действующее лицо - *__пользователь__* или *__он__* в любом из шагов

[source,]
----
    * ()
    
    # действие с параметром
    * () ""
    * () с параметром ""

    # действие с двумя параметрами
    * () "" ""
    * () с параметрами "" ""
    
    # действие с тремя параметрами
    * () "" "" ""
    * () с параметрами "" "" ""

    # действия с таблицей данных (DataTable)
    * () данными
    * () "" данными
    
    # действие со списком
    * () из списка
----
