=== Методы для работы с элементами

`Html plugin` предоставляет ряд методов для работы с блоками и типизированными элементами

Обратиться к ним можно через `Environment.getReflection()`


[width="100%",options="header"]
|====================
| **Метод** | **Описание**
| boolean isChildOf(Class<?> parent, Field field)
| Получает тип поля и проверяет, что он является дочерним для переданного типа


| <T extends WebElement> T findElementInBlockByTitle(Page page, String blockPath, String title, Class<T> type)
| Находит элемент на заданной странице требуемого типа в указанном блоке. 
В качестве блока можно указать непосредственно имя блока или путь до него, если он находится во вложенной структуре блоков.
Путь задается через разделитель “->”

Обратите внимание, что в случае, если разделитель присутствует в имени блока, то имя будет воспринято как два следом идущих блока.

Если элемент не найден, или найден, но с не соответствующим типом, то будет выброшено исключение


| <T extends WebElement> List<T> findListOfElements(String listTitle, Class<T> type, Object context)
| Находит список элементов требуемого типа в заданном контексте в указанном блоке. 

Если список элементов не найден, или найден, но с не соответствующим типом, то будет выброшено исключение


| HtmlElement findBlock(Page page, String blockPath)
| Выполняет поиск блока по имени или пути на переданной странице.

В качестве блока можно указать непосредственно имя блока или путь до него, если он находится во вложенной структуре блоков.
Путь задается через разделитель “->”

Обратите внимание, что в случае, если разделитель присутствует в имени блока, то имя будет воспринято как два следом идущих блока.

Если блок не найден, то будет выброшено исключение


| List<HtmlElement> findBlocks(Page page, String blockPath)
| Выполняет поиск списка блоков по имени или пути на переданной странице.

В качестве списка блоков можно указать непосредственно имя списка блоков или путь до него, если он находится во вложенной структуре блоков.
Путь задается через разделитель “->”

Обратите внимание, что в случае, если разделитель присутствует в имени списка блоков, то имя будет воспринято как два следом идущих блока.

Если блок не найден, то будет выброшено исключение


| void executeMethodByTitleInBlock(Page page, String block, String actionTitle)
| Выполняет глагольное выражение в указанном блоке с заданной страницы.  

В качестве списка блоков можно указать непосредственно имя списка блоков или путь до него, если он находится во вложенной структуре блоков.
Путь задается через разделитель “->”


| void executeMethodByTitleInBlock(Page page, String blockPath, String actionTitle, Object... parameters)
| Выполняет глагольное выражение с параметрами в указанном блоке с заданной страницы.  

В качестве списка блоков можно указать непосредственно имя списка блоков или путь до него, если он находится во вложенной структуре блоков.
Путь задается через разделитель “->”


| <T extends TypifiedElement> T getTypifiedElementByTitle(Page page, String title)
| Выполняет поиск типизированного элемента по имени на заданной странице


| <T> T getElementByField(Object parentObject, Field field)
| Возвращает элемент поля
|====================
