=== Тестовые сценарии
*__Тестовый сценарий__* - это совокупность шагов, конкретных условий и параметров, необходимых для проверки реализации тестируемой функции или её части

*__Фича__* - набора сценариев, имеющих общую функциональность. Фичи представляют собой файлы с расширением `feature`, написанные на языке `Gherkin` с использованием возможностей фреймворка `Cucumber`

С учетом локализации шагов, фичи могут быть написаны по крайней мере на одном из двух языков: русском или английском

Рассмотрим структуру фичи на примере:
[source,]
----
#language:ru
@feature-tag
Функционал: Тестирование поиска Google

  Предыстория: 
    Когда открывается страница "Главная страница"
    
  @test-tag
  Сценарий: Тестирование поиска
    И пользователь (тестирует) "Элемент"    
    
  @test-tag-examples
  Структура сценария: Тестирование поиска
    И пользователь (тестирует) "<element>"
    
  Примеры:
    | element   |
    | Элемент 1 |
    | Элемент 2 |
----

*__#language:ru__* - язык фичи

*__@feature-tag__* - тэг запуска фичи. Позволяет запустить все тестовые сценарии фичи одной группой. Может быть любым, но обязан всегда начинаться с `@`

*__Функционал (Feature:)__* - описание функциональности фичи

*__Предыстория: (Background:)__* - шаги, которые будут выполняться перед каждым тестовым сценарием

*__@test-tag и @test-tag-examples__* - тэги запуска тестов. Могут быть любыми, но обязаны всегда начинаться с `@`

NOTE: На одном сценарии может быть сколько угодно тэгов + 
 + 
Не рекомендуется использовать на разных сценариях или фичах только одинаковые тэги. Всегда должна быть возможность запустить любой тест отдельно от остальных


*__Сценарий: (Scenario:)__* - описание функциональности тестового сценария

*__Структура сценария: (Scenario Outline:)__* - описание функциональности тестового сценария. Используется при параметризации тестов в связке с ключевым словом `Примеры:`

*__Шаги и глагольные выражения__*  тестового сценария. Начинаются сразу после ключевого слова `Сценарий:`. Шаги должны начинаться с ключевых слов, таких как `Если`, `Когда`, `Тогда` (`Given`, `When`, `Then`) либо с `*`. Для работоспособности не имеет значения, какое ключевое слово используется, но они позволяют сделать фичи более удобными для чтения

WARNING: Чтобы использовать элемент или глагольное выражение, нужно обозначить текущий контекст — страницу. Сделать это можно, например, шагом "открывается страница"

*__Примеры: (Examples:)__* - используются для параметризации тестового сценария. Значения подставляются по имени параметра. В нашем примере тест бы выполнился два раза: сначала с "Элемент 1", затем с "Элемент 2" 


NOTE: Рекомендации: + 
 + 
 1. Каждый сценарий должен быть независим от всех остальных, то есть его можно запустить независимо от остальных и он выполнится успешно +  
 + 
 2. Лучше всего разбивать сценарии на группы по их функциональности, чтобы фичи были небольшими. Это значительно упростит поддержку автотестов в дальнейшем




