==== Создание и инициализация кастомных элементов

:t: Обратиться к методам можно через `HtmlElementUtils`

{t}

Иногда возникают ситуации, когда нужно из имеющегося или только что найденного веб элемента создать кастомный

При создании стандартными методами через конструктор элемент не будет инициализирован на странице и, как следствие, не будут инициализированы элементы его внутренней структуры и не получится использовать его методы

Чтобы этого избежать, можно использовать метод создания кастомного элемента

|====================
| *Метод* | *Описание*
| static <T extends TypifiedElement> T createElementWithCustomType(Class<T> clazz, WebElement element)
| Создает элемент с заданным кастомным типом из `WebElement` и инициализирует его на текущей странице
|====================

==== Получение `WebElement`

{t}

|====================
| *Метод* | *Описание*
| static <T extends WebElement> WebElement getWebElement(T element) 
| Возвращает элемент типа `WebElement` из типизированного элемента

Если элемент уже имеет тип `WebElement`, то вернет его

Если элемент является наследником `TypifiedElement`, то получит `WebElement` через `getWrappedElement()`
|====================