=== Запоминание значений переменных
Значение переменной можно запомнить используя специальную аннотацию `@Stashed`.

Значения в `Stash` хранятся в виде пар ключ-значение. В качестве ключа может выступать имя переменной, на которую навешана аннотация `@Stashed`, или заданное текстовое значение

Пример запоминания значения с ключем-именем переменной:

[source,]
----
@Stashed(by = By.NAME)
private String stashByName = "Это запоминаемое значение";
----

Взять запомненное значение можно по ключу следующим образом:

[source,]
----
Stash.getValue("stashByName");
----

Пример сзаданием имени ключа:

[source,]
----
@Stashed(by = By.TITLE, title = "Это ключ")
private String stashByTitle = "Это запоминаемое значение";
----

Взять запомненное значение можно по ключу следующим образом:

[source,]
----
Stash.getValue("Это ключ");
----
 

WARNING: [red]#Если положить в Stash значение с ключем, который уж использовался, предыдущее значение затрется + 
 + 
Stash существует в пределах одного запуска. Поэтому рекомендуется не использовать в различных тестах одни и те же ключи значений#