== Rest plugin
Плагин для автоматизации API приложений, базирующийся на `rest-assured` и `cucumber`

Основная идея заключается в том, что каждый метод API описывается отдельным классом, в котором есть поля запроса и методы валидации

В качестве паттерна проектирования взят PageObject. Перекладывая идеи этого паттерна с GUI тестирования, на тестирование API для каждого метода API в приложении с автотестами создается свой класс, где описываются нужные поля запроса и методы валидации. Основное преимущество данного паттерна - это простота поддержки автотестов, ведь в случае изменения полей объекта API, изменения нужно внести в одном месте, где он описан.

Использование же BDD позволяет писать сценарии автоматизированного тестирования на человекочитаемом языке, что позволяет понизить входной порог для разработчиков автотестов, и позволяет людям, не знакомым с языками программирования и автоматизацией тестирования, понять и воспроизвести шаги автотеста в ручную.

:plug: rest-plugin

include::web_how_to_start.asciidoc[]

В файле `application.properties` в параметре `api.baseURI` прописать путь тестируемого приложения. Например:

[source,]
----
api.baseURI = http://api.com
----

include::rest_entries.asciidoc[]
include::rest_entries_param.asciidoc[]
include::rest_entries_examples.asciidoc[]

верификация
шаги отправки и верификации

include::rest_build_request.asciidoc[]

Пример??



