==== Шаги тестовых сценариев
Под шагами(Step Definitions) предполагаются стандартные шаги тестовых сценариев, описанных по логике работы с `cucumber`

`{plug}` содержит набор стандартных шагов, необходимых для автоматизации любого проекта. Step Definitions, которые уже есть во фреймворке, поддерживают локализацию на двух языках: русском и английском

Ниже приведен список доступных шагов с описанием и примерами:

NOTE: Перед шагом можно прописать действующее лицо - *__пользователь__* или *__он__* в любом из шагов, предполагающих что кто-либо совершает какое-либо действие, например *__заполняет поле__*

include::web_plugin_steps.asciidoc[]
include::web_core_steps.asciidoc[]

О том как писать свои шаги, можно узнать в документации link:https://docs.cucumber.io/guides/10-minute-tutorial[cucumber]

WARNING: [red]#Чтобы использовать свои шаги, нужно в файле запуска тестов прописать путь до них через запятую в опцию `glue`#

====
Рекомендации::
* Параметры рекумендуется задавать регэкспом `"([^\"]*)\"`
* Если шаг используется только на одной странице, лучше описать глагольное выражение на странице
* Шаги лучше хранить в каталоге отдельном от страниц (как правило, `stepdefs`) в классах, разбив их на логичесике группы, чтобы быстро и удобно находить их в зависимости от функциональности или принадлежности
====

include::web_fluent.asciidoc[]

===== Шаги в английской локализации
include::web_plugin_steps_en.asciidoc[]
include::web_core_steps_en.asciidoc[]
