==== Глагольные выражения
`{plug}` позволяет описывать шаги, свойственные отдельной странице, непосредственно на ней. Такие шаги называются глагольными выражениями. Они имеют базу в фреймворке и за счет этого их описание сводится к простому именованию методов через специальную аннотацию - `@ActionTitle`. 

Пример::
[source, subs="attributes+"]
----
@PageEntry(title = "Ваша страница")
public abstract class YourPage extends {pn} {

    @ActionTitle(value = "тестирует")
    public void check() {
        ....
    }
}
----

Чтобы использовать глагольное выражение в тестовом сценарии, достаточно указать его имя в круглых скобках в контексте страницы. Например:

[source,]
----
* открывается страница "Ваша страница"
* (тестирует)
----

Одно глагольное выражение может иметь несколько именований. В этом может быть необходимость, когда есть желание внести конкретику в тестовом сценарии. Сделать это можно при помощи аннотации `@ActionTitles` Например:

[source, subs="attributes+"]
----
@PageEntry(title = "Ваша страница")
public abstract class YourPage extends {pn} {
    
    @ActionTitles({
        @ActionTitle(value = "тестирует"),
        @ActionTitle(value = "тестирует вашу страницу")
    })
    public void check() {
        ....
    }
}
----

Глагольные выражения могут иметь какие угодно параметры для этого достаточно добавить параметр в сигнатуре метода. Например:

[source, subs="attributes+"]
----
@PageEntry(title = "Ваша страница")
public abstract class YourPage extends {pn} {

    @ActionTitle(value = "тестирует с параметром")
    public void check(String param) {
        ....
    }
}
----

====
При написании глагольных выражений важно помнить::
* Значение, возвращаемое методом, никуда не сохраняется, поэтому в качестве типа возвращаемого значения стоит всегда указывать void
* В качестве параметров метода можно использовать следующие типы: String, List<String>, DataTable
* Если шага с нужным набором параметров для вашего экшена нет, вы можете написать его сами
====

===== База для глагольных выражений
Как уже говорилось выше, глагольные выражения базируются на уже описанных в `{plug}`шагах особой структуры. Они приведены ниже

NOTE: Перед шагом можно прописать действующее лицо - *__пользователь__* или *__он__* в любом из русскоязычных шагов


[width="100%",options="header"]
|====================
^.^| RU ^.^| EN 
2.1+^.^|  Действие без параметров
| * () 
|  * user ()

2.1+^.^| Действие с параметром 
| * () "" + 
* () с параметром "" 
| * user () "" +  
* user () with param "" 

2.1+^.^| Действие с двумя параметрами
| * () "" "" + 
* () с параметрами "" "" 

| * user () "" "" + 
* user () with the parameters "" "" 

2.1+^.^| Действие с тремя параметрами
| * () "" "" "" + 
* () с параметрами "" "" ""
| * user () "" "" "" + 
* user () with the parameters "" "" "" 
  
2.1+^.^| Действия с таблицей данных (DataTable)
| * () данными + 
* () "" данными 
| * user () data + 
* user () "" data

2.1+^.^| Действие со списком
| * () из списка 
| * user () from the list 
|====================
