== Mobile plugin

Плагин для автоматизации тестирования мобильных приложений (Android). Базируется на `appium` и `cucumber`.

Для запуска тестов необходим запущенный эмулятор android-устройства (или подключенное реальное android-устройство) и запущенный appium-сервер.

Подробности по установке и запуску эмуляторов можно найти здесь:
https://developer.android.com/studio/run/emulator

Подробности по установке и запуску appium-сервера можно найти здесь:
https://github.com/appium/appium/blob/master/docs/en/about-appium/getting-started.md

:plug: mobile-plugin
:pn: MobilePage
:st: MobileSteps
:stg: MobileStepsImpl
:act: MobilePageActions
:ref: DefaultReflection

include::web_how_to_start.asciidoc[]

include::mobile_properties.asciidoc[]

include::web_pages.asciidoc[]

include::web_elements.asciidoc[]

=== Методы работы с элементами

include::web_element_utils.asciidoc[]

=== Шаги и глагольные выражения

Использовать элементы в тестовых сценариях можно двумя способами: в шагах либо в глагольных выражениях

include::mobile_steps.asciidoc[]

include::web_actions.asciidoc[]

include::cucumber_doc.asciidoc[]

include::allure.asciidoc[]

=== Вспомогательные методы

include::web_reflection.asciidoc[]

=== Параллельный запуск тестов на симуляторах
Будет описан метод при использовании Selenium Grid.

==== Скачать и запустить selenium-server-standalone
Скачать здесь
[source,]
----
https://www.seleniumhq.org/download/
----

Запустить
[source,]
----
java -jar selenium-server-standalone-3.141.59.jar -role hub
----

==== Сконфигурировать и запустить по экземпляру appium на каждый симулятор
Будет приведен пример для двух симуляторов.

Запуск первого экземпляра appium
[source,]
----
appium -p 4723 --nodeconfig <path_to_config_file>/node-config-4723.json --default-capabilities <path_to_capability_file>/node-capabilities-4723.json
----
node-config-4723.json
[source,]
----
{
  "capabilities": [
    {
      "maxInstances": 1,
      "platformName": "ios"
    }
  ],
  "configuration": {
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url": "http://<хост_где_будет_открыт_экземпляр_аппиума>:4723/wd/hub",
    "host": "<хост_где_будет_открыт_экземпляр_аппиума>",
    "port": 4723,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "<хост_где_открыт_selenium-standalone>",
    "hubProtocol": "http"
  }
}
----
node-capabilities-4723.json
[source,]
----
{
  "deviceName": "11 Pro 13.0",
  "platformVersion": "13.0",
  "wdaLocalPort": 8100
}
----

Запуск второго экземпляра appium
[source,]
----
appium -p 4724 --nodeconfig <path_to_config_file>/node-config-4724.json --default-capabilities <path_to_capability_file>/node-capabilities-4724.json
----
node-config-4724.json
[source,]
----
{
  "capabilities": [
    {
      "maxInstances": 1,
      "platformName": "ios"
    }
  ],
  "configuration": {
    "cleanUpCycle": 2000,
    "timeout": 30000,
    "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
    "url": "http://<хост_где_будет_открыт_экземпляр_аппиума>:4724/wd/hub",
    "host": "<хост_где_будет_открыт_экземпляр_аппиума>",
    "port": 4724,
    "maxSession": 1,
    "register": true,
    "registerCycle": 5000,
    "hubPort": 4444,
    "hubHost": "<хост_где_открыт_selenium-standalone>",
    "hubProtocol": "http"
  }
}
----
node-capabilities-4724.json
[source,]
----
{
  "deviceName": "iPhone Xs",
  "platformVersion": "12.1",
  "wdaLocalPort": 8101
}
----

==== Внести правки в application.properties
В качестве appium.url указать адрес на котором открыт selenium-standalone.

Удалить параметры
[source,]
----
appium.device.name = ...
appium.device.platform.name = ...
appium.device.platform.version = ...
----

==== Внести правки в pom.xml
Добавить в surefire plugin следующую конфигурацию
[source,]
----
<configuration>
    <parallel>methods</parallel>
    <threadCount>4</threadCount>
</configuration>
----

Более подробную информацию можно найти по ссылке
https://cucumber.io/docs/guides/parallel-execution/#junit
